### ISSUE TITLE
more updates for People page

### ISSUE THREAD

**Issue by plzmsu** [srm-ecology/srm-ecology-website#11]
@billspat - a few more people have added their info for the People page. Can you upload (is there a process for this other than exporting csv?) Also note the html / Rmd scripting for weblinks is still not updated on the Google Sheet for my entry.

**Comment by billspat** [comment]
page is updated with data as of 1pm today (including Shan's changes in his pull request).   Your links are in your bio as I put the Markdown directly in the google sheet (and others can do the same). The script to import from google sheets is here : https://gist.github.com/billspat/bf743857b512e45f69890320d3062bd0
