### ISSUE TITLE
add PNAS accepted article to Publications page when published

### ISSUE THREAD

**Issue by plzmsu** [srm-ecology/srm-ecology-website#12]
I think we should add the full citation for our accepted PNAS article to Publications page - I couldn't find the format to do this

**Comment by billspat** [comment]
The format for publications is documented here https://wowchemy.com/docs/content/publications/ (I'll add to the README) but the theme does not have a good way to add citations of pre-published work.   

I suggest leaving this on the About page as it is in the google doc, then adding to "publications"  when it's published in a few days

**Comment by plzmsu** [comment]
Zarnetske, P.L., J. Gurevitch, J. Franklin, P. Groffman, C. Harrison, J. Hellmann, F. Hoffman, S. 
Kothari, A. Robock, S. Tilmes, J. Wu, D. Visioni, L. Xia, and C.-E. Yang. In Press. Potential ecological impacts of climate intervention by reflecting sunlight to cool Earth. Proceedings of the National Academy of Sciences.

**Comment by billspat** [comment]
added in as "in press" on a new publication page.  The formatting is not great for pubs for this theme - it's built assuming you will have many publications (e.g. a CV) but the information is there.

**Comment by billspat** [comment]
closed with 48c7464321f5d76600bfe1de531345f8629bd1f3  which adds a new publications sections and menu item. https://www.climateinterventionbiology.org/publication/

**Comment by plzmsu** [comment]
Thanks - the "P.L." is not showing up next to my name in the beginning of the citation.

**Comment by billspat** [comment]
unfortunately, the theme meddles with the author list, so for now I've simply put your initials in front of your name.   That's not standard format but it's a website, not a CV,  so I think it will be ok
