### ISSUE TITLE
Events: AAAS people listed

### ISSUE THREAD

**Issue by plzmsu** [srm-ecology/srm-ecology-website#13]
@billspat I tried to edit the People listed to include more on the AAAS page, but it's not updating (only showing Phoebe and Cheng-En)

**Comment by billspat** [comment]
from Cheng-En:

For the AAAS conference part, my suggestion is to list organizers, moderator, speakers, and respondents each in different lines.
By accessing the Panel Session at AAAS here, I see a caption of "AAAS Logo" on the bottom right of the logo. From the same webpage, as Forrest mentioned, the first and the last names of Forrest's and Cheryl's are missing a white space; the personal pages are not linked properly by clicking Forrest's or Cheryl's names.

**Comment by billspat** [comment]
The event or blog post "authors" use the "username" which is the folder the data is in (and in the folder I have no spaces).  I think best way is to not use the front-matter "authors"  list for posts or events and put people's names directly into the body of the text.     closed with 6ae7ac5228ce51ec482344b592442137a7df1813
