### ISSUE TITLE
add 2 images to home welcome.md

### ISSUE THREAD

**Issue by plzmsu** [srm-ecology/srm-ecology-website#18]
@billspat how do we add 2 images to welcome.md? I confirmed with our corresponding author that since we're going to be doing open access, we can publish the figs from the article. So, I added the diagram back. But how do you add another image? I'd like to move: maps_projected_global_surface_temp_precip.jpg to "About" and I'd like to put "SAI_temp_explanations.jpg" on the welcome.md, below "SRM-Ecology-Effects-Diagram-web.jpg"

**Comment by billspat** [comment]
You need to create an additional widget for home.   I can add the image this afternoon  - it may be easier to do it than explain it!  

It will look best if there is additional text to the side of the image (it will be normaal sized text)

**Comment by plzmsu** [comment]
Yes, that image (maps_projected_global_surface_temp_precip.jpg) already has a caption, but if it's too much off to the side, we can just leave it on the About page:

Projected surface temperature change in 2081-2100 in a scenario without mitigation compared with one where emissions are reduced (left), and in a scenario without mitigation but with stratospheric aerosol injections (SAI) (right). Although SAI may cool the planet down to a certain global temperature target, the local cooling may be uneven, and there are potentially large impacts on ecosystems (right). Adapted from Visioni et al. (2021)

**Comment by billspat** [comment]
Image added - see 8df30cc011b663153c0f1463cb2dedb101ebcc5a

) there is a new file home/figure.md that has the figure on the home page (welcome.md is a 'hero' widget and can only have 1 image.  

)  Does there need to be a short 'title' above the image ?

) I did not remove the balloon image, I simply placed the temp+precip map in place of the previous map.

**Comment by billspat** [comment]
I forgot to ask if the current image placement looks good, but not hearing otherwise I'm closing this issue.  Re-open if you'd like to make adjustments
