### ISSUE TITLE
Better image for home page?

### ISSUE THREAD

**Issue by billspat** [srm-ecology/srm-ecology-website#2]

**Comment by dan-visioni** [comment]
![maps_phoebe](https://user-images.githubusercontent.com/63248921/106362370-6b7d9f00-62f0-11eb-9208-f417a9c14de6.png)
This is the one I made for Phoebe's press release, if you like it more.

**Comment by billspat** [comment]
@dan-visioni I do like both of these images - they are informative and beautiful!    I started this issue because both of these images show the benefit of SRM but to me they don't illustrate the unintended, ecological consequences (at least at first glance) which I was I thought the purpose of the working group and the main message to be communicated first.   I put Phoebe's diagram there first but would love to see these on the about page or other page.   But this is just my editorial/outsider opinion!  
 
 We can add more text on the home page that includes this image, by adding a new html file in the /home folder, call it something like "project_detail.html"  and setting the  front matter to make it basic text 

```
widget: blank
active: true
headless: true
weight: 15
# etc
---
```

then you could add another `<figure>` element like the about page.

**Comment by plzmsu** [comment]
I think Daniele's images should also go on the first page, or they should go on the "About" page. Currently, the "About" page image is  maybe not the best depiction of what SRM or SAI is...

**Comment by dan-visioni** [comment]
![maps_phoebe](https://user-images.githubusercontent.com/63248921/106518653-36b44800-64a8-11eb-97a4-4f3710d7554b.png)
See if you like this more. Caption: 
"Projected surface temperature changes (upper panels) and precipitation changes (lower panels) in 2080-2100
comparing a world with high emissions (SSP5-8.5, ~1100 ppm CO2) versus one with lower emissions (SSP2-4.5, ~600 ppm CO2) (left panels) and a world with high emissions but temperatures cooled using sulfate aerosols at the same levels as SSP2-4.5. Output from CMPI6 models participating in the Geoengineering Model Intercomparison Project (Visioni et al., 2021)."

**Comment by billspat** [comment]
email from Phoebe: 

"Until PNAS publication is deems open access, let’s replace those images with others (the one on Home page and the one on About with the 2-panel SAI scenarios).
 
@dan-visioni  I’ll let you decide what to put up instead. You’ve made some nice ones with the maps! Hopefully we can still use the ones we had originally thought of but if PNAS doesn’t allow it, then we will have others. I am currently making one with photos of ecosystem photos, so maybe we can use that in place of the Home page one."

to add an image to the home page, add the filename of the image that is in  /static/media ) for the value of the "hero_media:" in the front matter of "content/home/welcome.md"  - just the filename (no folder necessary).

**Comment by billspat** [comment]
Phoebe updated the image and I made it a jpg and smaller file size.  Closing this for now!
