### ISSUE TITLE
update People page: add Simone Tilmes

### ISSUE THREAD

**Issue by plzmsu** [srm-ecology/srm-ecology-website#20]
Add Simone Tilmes.
@billspat I don't have python installed/not following the process for adding people/ can't find how to do it.

**Comment by billspat** [comment]
added f166a02

Now that the people pages are complete - for updates  or adding/removing individuals I would edit pages directly in '/content/authors/<person>/_index.md'

**Comment by billspat** [comment]
I also updated the readme with instructions for editing/adding people.
