### ISSUE TITLE
need to add link to PNAS publication online, change to full citation w year

### ISSUE THREAD

**Issue by plzmsu** [srm-ecology/srm-ecology-website#23]
@billspat 
Finally our paper is out! I wasn't sure how to add a link to the paper online @ PNAS. Can you add it in Publications? Could also be a News item since it's our first paper.

link: https://www.pnas.org/content/118/15/e1921854118 

Here is the updated citation: 

Zarnetske, Phoebe L., Jessica Gurevitch, Janet Franklin, Peter M. Groffman, Cheryl S. Harrison, Jessica J. Hellmann, Forrest M. Hoffman, et al. “Potential Ecological Impacts of Climate Intervention by Reflecting Sunlight to Cool Earth.” Proceedings of the National Academy of Sciences 118, no. 15 (April 13, 2021). https://doi.org/10.1073/pnas.1921854118.

**Comment by billspat** [comment]
closing with 7059bf24e6242b61d056537eb0ae272aa7228494 and 7c3677349bdf8e71f87db9243a06ff2277e08d95   I added the full abstract to the pub page, and split it so that the first part shows up on the "publications list" page (which is a list of one).    I also added the news item on the home page.
